### ISSUE TITLE
[FEAT] 온보딩 닉네임 유효성 검증 API 구현

### ISSUE THREAD

**Issue by ckkim817** [TEAM-SEONYAK/SEONYAK-SERVER#61]
## 💡 Issue

- 온보딩 시 닉네임 유효성에 대해 검증하는 API를 구현합니다.

## 📝 To-do

- [x] DTO(Record) 정의
- [x] Service 클래스 작성
- [x] Controller 클래스 작성
- [x] 공통 응답 처리 및 예외 처리
