### ISSUE TITLE
[FEAT] BaseTimeEntity + 학교 이메일 인증 API 연동

### ISSUE THREAD

**Issue by seokbeom00** [TEAM-SEONYAK/SEONYAK-SERVER#64]
## 💡 Issue
* 기존 엔티티에 누락된 BaseTimeEntity 생성
* 학교 이메일 인증 외부 API 연동

## 📝 To-do
- [x] BaseTimeEntity 구현
- [x] Feign 연동 설정 개선
- [x] 학교 이메일 인증 코드 발송 API 연동
- [x] 학교 이메일 인증 코드 확인 API 연동
