### ISSUE TITLE
[FEAT] 휴대전화 번호 인증 API 구현

### ISSUE THREAD

**Issue by ckkim817** [TEAM-SEONYAK/SEONYAK-SERVER#66]
## 💡 Issue

1. 휴대전화 번호로 인증번호를 발송합니다.
2. 유저가 받아서 입력한 인증번호가 올바른지 확인합니다.

## 📝 To-do

- [x] 도메인 모델(Entity) 정의
- [x] DTO(Record) 정의
- [x] Repository 인터페이스 생성
- [x] Service 클래스 작성
- [x] Controller 클래스 작성
- [x] 공통 응답 처리 및 예외 처리
