### ISSUE TITLE
[FEAT] 선배 프로필 등록 구현

### ISSUE THREAD

**Issue by seokbeom00** [TEAM-SEONYAK/SEONYAK-SERVER#68]
## 💡 Issue
* 선배가 프로필 등록시에 등록한 선호시간대를 조회하는 API

## 📝 To-do
- [x] 선호 프로필 등록 컨트롤러 구현
- [x] JSONB 어노테이션으로 개선
- [x] 선호 프로필 등록 서비스 구현
- [x] 선호 프로필 등록 레포지토리 구현
