### ISSUE TITLE
[FEAT] 학교, 학과 검색 API 구현

### ISSUE THREAD

**Issue by ckkim817** [TEAM-SEONYAK/SEONYAK-SERVER#77]
## 💡 Issue

- 학교 검색 API를 구현합니다.
- 학과 검색 API를 구현합니다.

## 📝 To-do

- [x] DTO(Record) 정의
- [x] Repository 인터페이스 생성
- [x] Service 클래스 작성
- [x] Controller 클래스 작성
