### ISSUE TITLE
[FEAT] 회원가입 API 구현

### ISSUE THREAD

**Issue by ckkim817** [TEAM-SEONYAK/SEONYAK-SERVER#82]
## 💡 Issue

- 회원가입 API를 구현합니다. (선배/후배 구분)

## 📝 To-do

- [x] DTO(Record) 정의
- [x] Service 클래스 작성
- [x] Controller 클래스 작성
