### ISSUE TITLE
[FEAT] 구글 미트 회의실 링크 조회 API 구현

### ISSUE THREAD

**Issue by ckkim817** [TEAM-SEONYAK/SEONYAK-SERVER#84]
## 💡 Issue

- 구글 미트 회의실 링크 조회하는 API를 구현합니다.

## 📝 To-do

- [x] DTO(Record) 정의
- [x] Service 클래스 작성
- [x] Controller 클래스 작성
- [x] 공통 응답 처리 및 예외 처리
