### ISSUE TITLE
[FEAT] 선배 상세 프로필 조회 API 구현

### ISSUE THREAD

**Issue by ckkim817** [TEAM-SEONYAK/SEONYAK-SERVER#86]
## 💡 Issue

- 선배 상세 프로필 조회 API를 구현합니다.

## 📝 To-do

- [x] DTO(Record) 정의
- [x] Service 클래스 작성
- [x] Controller 클래스 작성
