### ISSUE TITLE
[FEAT] 약속 상세 페이지 조회 API 구현

### ISSUE THREAD

**Issue by ckkim817** [TEAM-SEONYAK/SEONYAK-SERVER#88]
## 💡 Issue

- 약속 상세 페이지 조회 API를 구현합니다.

## 📝 To-do

- [x] DTO(Record) 정의
- [x] Repository 인터페이스 생성
- [x] Service 클래스 작성
- [x] Controller 클래스 작성
- [x] 공통 응답 처리 및 예외 처리
